== Problem #1 [3/06/2017]
Looks like the `limit` parameter causes the client to crash:
-------
Traceback (most recent call last):
  File "show_billable_resources.py", line 39, in <module>
    main()
  File "show_billable_resources.py", line 30, in main
    print( cclient.samples.list( q=query_samples, limit=1 ) )
  File "/usr/local/lib/python2.7/site-packages/ceilometerclient/v2/samples.py", line 49, in list
    return self._list(options.build_url(path, q, params))
  File "/usr/local/lib/python2.7/site-packages/ceilometerclient/common/base.py", line 63, in _list
    resp = self.api.get(url)
  File "/usr/local/lib/python2.7/site-packages/ceilometerclient/apiclient/client.py", line 355, in get
    return self.client_request("GET", url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/ceilometerclient/apiclient/client.py", line 345, in client_request
    self, method, url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/ceilometerclient/apiclient/client.py", line 261, in client_request
    method, self.concat_url(endpoint, url), **kwargs)
  File "/usr/local/lib/python2.7/site-packages/ceilometerclient/apiclient/client.py", line 201, in request
    raise exceptions.from_response(resp, method, url)
ceilometerclient.apiclient.exceptions.BadRequest: Unknown argument: "limit" (HTTP 400) (Request-ID: req-c136d259-990c-476d-9b8b-1a928658be15)
-------

== Solution to problem #1 [3/06/2017]
A new class responsible for interacting with the Ceilometer's API and using the `requests` Python library has been written from scratch.

== Problem #2 [5/06/2017]
The format of the input file with queries has a convoluted formatting and only supports the "=" operator for now.

== Problem #3 [5/06/2017]
The file with queries can't have an empty "queries" column, as the current code always breaks the input line into a 3-object tuple:

-------
Traceback (most recent call last):
  File "show_billable_resources.py", line 46, in <module>
    main()
  File "show_billable_resources.py", line 35, in main
    (meter_name, limit, query_params) = line.strip().split('\t')
ValueError: need more than 2 values to unpack
-------
A workaround for this bug is to always add a parameter like `project_id` to the "queries" column.
